spring:
  application:
    name: bi-proj
  # 默认 dev 环境
  profiles:
    active: dev
  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # session 配置
  session:
    # todo 取消注释开启分布式 session（须先配置 Redis）
    # store-type: redis
    # 30 天过期
    timeout: 2592000
  # 数据库配置
  # todo 需替换配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:
    username:
    password:
  # Redis 配置
  # todo 需替换配置，然后取消注释
  redis:
     database:
     host:
     port:
     timeout:
  # Elasticsearch 配置
  # todo 需替换配置，然后取消注释
#  elasticsearch:
#    uris: http://localhost:9200
#    username: root
#    password: 123456
  # 文件上传
  servlet:
    multipart:
      # 大小限制
      max-file-size:
  rabbitmq:
    host:
    port:
    password:
    username:
server:
  address:
  port:
  servlet:
    context-path:
    # cookie 30 天过期
    session:
      cookie:
        max-age:
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl:
  global-config:
    db-config:
      logic-delete-field:
      logic-delete-value:
      logic-not-delete-value:
# 微信相关
wx:
  # 微信公众平台
  # todo 需替换配置
  mp:
    token: xxx
    aesKey: xxx
    appId: xxx
    secret: xxx
    config-storage:
      http-client-type: HttpClient
      key-prefix: wx
      redis:
        host: 127.0.0.1
        port: 6379
      type: Memory
  # 微信开放平台
  # todo 需替换配置
  open:
    appId: xxx
    appSecret: xxx
# 对象存储
# todo 需替换配置
cos:
  client:
    accessKey: xxx
    secretKey: xxx
    region: xxx
    bucket: xxx
# 接口文档配置
knife4j:
  enable: true
  openapi:
    title: "接口文档"
    version: 1.0
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.yuheng.springbootinit.controller
## 讯飞 AI 配置
xun-fei:
  client:
    appId:
    apiSecret:
    apiKey:

